name: Tests

on:
  push:
      branches:
      - dev
      - main

jobs:
    hello-world:
        runs-on: ubuntu-20.04
    unit-test:
        runs-on: ubuntu-20.04
        container: docker://epitechcontent/epitest-docker

        steps:
          - name: Say hello world
            shell: bash
            run: echo Welcome to the GitHub Actions workshop !

          - name: Checkout
            uses: actions/checkout@v2

          - name: Run tests
            shell: bash
            run: make tests_run

          - name: Get Coverage
            shell: bash
            run: make coverage
